// 部位ごとに選択できるトレーニング種目を管理する場所
export const exercisesByBodyPart = {
  胸: {
    胸上部: [
      { id: "incline-barbell-bench-press", name: "インクラインバーベルベンチプレス", equipment: "バーベル" },
      { id: "incline-dumbbell-press", name: "インクラインダンベルプレス", equipment: "ダンベル" },
      { id: "incline-smith-bench-press", name: "インクラインスミスマシンベンチプレス", equipment: "スミスマシン" },
      { id: "incline-chest-press-machine", name: "インクラインチェストプレス", equipment: "マシン" },
      { id: "low-to-high-cable-fly", name: "ロー・トゥ・ハイケーブルフライ", equipment: "ケーブル" },
      { id: "incline-dumbbell-fly", name: "インクラインダンベルフライ", equipment: "ダンベル" },
      { id: "feet-elevated-push-up", name: "デクラインプッシュアップ", equipment: "自重" },
    ],
    胸中部: [
      { id: "barbell-bench-press", name: "バーベルベンチプレス", equipment: "バーベル" },
      { id: "dumbbell-bench-press", name: "ダンベルベンチプレス", equipment: "ダンベル" },
      { id: "smith-bench-press", name: "スミスマシンベンチプレス", equipment: "スミスマシン" },
      { id: "chest-press-machine", name: "チェストプレス", equipment: "マシン" },
      { id: "hammer-strength-chest-press", name: "ハンマーストレングスチェストプレス", equipment: "マシン" },
      { id: "dumbbell-fly", name: "ダンベルフライ", equipment: "ダンベル" },
      { id: "cable-fly", name: "ケーブルフライ", equipment: "ケーブル" },
      { id: "pec-deck-fly", name: "ペックデックフライ", equipment: "マシン" },
      { id: "push-up", name: "腕立て伏せ", equipment: "自重" },
      { id: "weighted-push-up", name: "加重腕立て伏せ", equipment: "自重" },
    ],
    胸下部: [
      { id: "decline-barbell-bench-press", name: "デクラインバーベルベンチプレス", equipment: "バーベル" },
      { id: "decline-dumbbell-press", name: "デクラインダンベルプレス", equipment: "ダンベル" },
      { id: "decline-smith-bench-press", name: "デクラインスミスマシンベンチプレス", equipment: "スミスマシン" },
      { id: "decline-chest-press-machine", name: "デクラインチェストプレス", equipment: "マシン" },
      { id: "high-to-low-cable-fly", name: "ハイ・トゥ・ローケーブルフライ", equipment: "ケーブル" },
      { id: "chest-dip", name: "チェストディップス", equipment: "自重" },
      { id: "decline-dumbbell-fly", name: "デクラインダンベルフライ", equipment: "ダンベル" },
    ],
    胸全体: [
      { id: "dumbbell-squeeze-press", name: "ダンベルスクイーズプレス", equipment: "ダンベル" },
      { id: "dumbbell-pullover-chest", name: "ダンベルプルオーバー", equipment: "ダンベル" },
      { id: "resistance-band-chest-press", name: "チューブチェストプレス", equipment: "チューブ" },
      { id: "resistance-band-fly", name: "チューブフライ", equipment: "チューブ" },
      { id: "close-grip-push-up-chest", name: "ナロープッシュアップ", equipment: "自重" },
    ],
  },
  背中: {
    広背筋: [
      { id: "pull-up", name: "懸垂", equipment: "自重" },
      { id: "chin-up", name: "チンニング（逆手）", equipment: "自重" },
      { id: "wide-grip-lat-pulldown", name: "ワイドグリップラットプルダウン", equipment: "ケーブル" },
      { id: "close-grip-lat-pulldown", name: "クローズグリップラットプルダウン", equipment: "ケーブル" },
      { id: "reverse-grip-lat-pulldown", name: "リバースグリップラットプルダウン", equipment: "ケーブル" },
      { id: "single-arm-lat-pulldown", name: "ワンハンドラットプルダウン", equipment: "ケーブル" },
      { id: "straight-arm-pulldown", name: "ストレートアームプルダウン", equipment: "ケーブル" },
      { id: "machine-pullover", name: "プルオーバーマシン", equipment: "マシン" },
      { id: "dumbbell-pullover-back", name: "ダンベルプルオーバー（背中）", equipment: "ダンベル" },
    ],
    背中中央: [
      { id: "barbell-row", name: "ベントオーバーバーベルロウ", equipment: "バーベル" },
      { id: "pendlay-row", name: "ペンドレイロウ", equipment: "バーベル" },
      { id: "t-bar-row", name: "Tバーロウ", equipment: "マシン" },
      { id: "seated-cable-row", name: "シーテッドケーブルロウ", equipment: "ケーブル" },
      { id: "single-arm-dumbbell-row", name: "ワンハンドダンベルロウ", equipment: "ダンベル" },
      { id: "chest-supported-dumbbell-row", name: "チェストサポートダンベルロウ", equipment: "ダンベル" },
      { id: "machine-row", name: "ロウイングマシン", equipment: "マシン" },
      { id: "inverted-row", name: "インバーテッドロウ", equipment: "自重" },
    ],
    僧帽筋: [
      { id: "barbell-shrug", name: "バーベルシュラッグ", equipment: "バーベル" },
      { id: "dumbbell-shrug", name: "ダンベルシュラッグ", equipment: "ダンベル" },
      { id: "smith-machine-shrug", name: "スミスマシンシュラッグ", equipment: "スミスマシン" },
      { id: "cable-shrug", name: "ケーブルシュラッグ", equipment: "ケーブル" },
      { id: "farmer-walk", name: "ファーマーズウォーク", equipment: "ダンベル" },
      { id: "face-pull", name: "フェイスプル", equipment: "ケーブル" },
    ],
    脊柱起立筋: [
      { id: "back-extension", name: "バックエクステンション", equipment: "自重" },
      { id: "weighted-back-extension", name: "加重バックエクステンション", equipment: "プレート" },
      { id: "reverse-hyperextension", name: "リバースハイパーエクステンション", equipment: "マシン" },
      { id: "barbell-good-morning", name: "グッドモーニング", equipment: "バーベル" },
      { id: "superman", name: "スーパーマン", equipment: "自重" },
    ],
    背中全体: [
      { id: "conventional-deadlift", name: "コンベンショナルデッドリフト", equipment: "バーベル" },
      { id: "sumo-deadlift", name: "スモウデッドリフト", equipment: "バーベル" },
      { id: "rack-pull", name: "ラックプル", equipment: "バーベル" },
      { id: "trap-bar-deadlift", name: "トラップバーデッドリフト", equipment: "トラップバー" },
      { id: "resistance-band-row", name: "チューブロウ", equipment: "チューブ" },
    ],
  },
  肩: {
    三角筋前部: [
      { id: "barbell-overhead-press", name: "バーベルオーバーヘッドプレス", equipment: "バーベル" },
      { id: "dumbbell-shoulder-press", name: "ダンベルショルダープレス", equipment: "ダンベル" },
      { id: "arnold-press", name: "アーノルドプレス", equipment: "ダンベル" },
      { id: "machine-shoulder-press", name: "ショルダープレスマシン", equipment: "マシン" },
      { id: "landmine-press", name: "ランドマインプレス", equipment: "バーベル" },
      { id: "dumbbell-front-raise", name: "ダンベルフロントレイズ", equipment: "ダンベル" },
      { id: "cable-front-raise", name: "ケーブルフロントレイズ", equipment: "ケーブル" },
    ],
    三角筋中部: [
      { id: "dumbbell-lateral-raise", name: "ダンベルサイドレイズ", equipment: "ダンベル" },
      { id: "cable-lateral-raise", name: "ケーブルサイドレイズ", equipment: "ケーブル" },
      { id: "machine-lateral-raise", name: "サイドレイズマシン", equipment: "マシン" },
      { id: "leaning-lateral-raise", name: "インクラインサイドレイズ", equipment: "ダンベル" },
      { id: "one-arm-cable-lateral-raise", name: "ワンハンドケーブルサイドレイズ", equipment: "ケーブル" },
      { id: "resistance-band-lateral-raise", name: "チューブサイドレイズ", equipment: "チューブ" },
    ],
    三角筋後部: [
      { id: "rear-delt-dumbbell-fly", name: "リアデルトダンベルフライ", equipment: "ダンベル" },
      { id: "reverse-pec-deck", name: "リバースペックデック", equipment: "マシン" },
      { id: "cable-rear-delt-fly", name: "ケーブルリアデルトフライ", equipment: "ケーブル" },
      { id: "face-pull-rear-delt", name: "フェイスプル（肩後部）", equipment: "ケーブル" },
      { id: "rear-delt-row", name: "リアデルトロウ", equipment: "ダンベル" },
      { id: "band-pull-apart", name: "バンドプルアパート", equipment: "チューブ" },
    ],
    肩全体: [
      { id: "push-press", name: "プッシュプレス", equipment: "バーベル" },
      { id: "smith-machine-shoulder-press", name: "スミスマシンショルダープレス", equipment: "スミスマシン" },
      { id: "pike-push-up", name: "パイクプッシュアップ", equipment: "自重" },
      { id: "handstand-push-up", name: "逆立ち腕立て伏せ", equipment: "自重" },
      { id: "plate-front-raise", name: "プレートフロントレイズ", equipment: "プレート" },
    ],
  },
  腕: {
    上腕二頭筋: [
      { id: "barbell-curl", name: "バーベルカール", equipment: "バーベル" },
      { id: "ez-bar-curl", name: "EZバーカール", equipment: "EZバー" },
      { id: "dumbbell-curl", name: "ダンベルカール", equipment: "ダンベル" },
      { id: "alternating-dumbbell-curl", name: "オルタネイトダンベルカール", equipment: "ダンベル" },
      { id: "hammer-curl", name: "ハンマーカール", equipment: "ダンベル" },
      { id: "incline-dumbbell-curl", name: "インクラインダンベルカール", equipment: "ダンベル" },
      { id: "preacher-curl", name: "プリーチャーカール", equipment: "EZバー" },
      { id: "cable-curl", name: "ケーブルカール", equipment: "ケーブル" },
      { id: "concentration-curl", name: "コンセントレーションカール", equipment: "ダンベル" },
      { id: "chin-up-biceps", name: "チンニング（上腕二頭筋）", equipment: "自重" },
    ],
    上腕三頭筋: [
      { id: "close-grip-bench-press", name: "ナローグリップベンチプレス", equipment: "バーベル" },
      { id: "ez-bar-skull-crusher", name: "EZバースカルクラッシャー", equipment: "EZバー" },
      { id: "dumbbell-french-press", name: "ダンベルフレンチプレス", equipment: "ダンベル" },
      { id: "cable-pushdown", name: "ケーブルプレスダウン", equipment: "ケーブル" },
      { id: "rope-pushdown", name: "ローププレスダウン", equipment: "ケーブル" },
      { id: "overhead-cable-extension", name: "オーバーヘッドケーブルエクステンション", equipment: "ケーブル" },
      { id: "dumbbell-kickback", name: "ダンベルキックバック", equipment: "ダンベル" },
      { id: "bench-dip", name: "ベンチディップス", equipment: "自重" },
      { id: "diamond-push-up", name: "ダイヤモンドプッシュアップ", equipment: "自重" },
      { id: "triceps-dip", name: "トライセプスディップス", equipment: "自重" },
    ],
    前腕: [
      { id: "barbell-wrist-curl", name: "バーベルリストカール", equipment: "バーベル" },
      { id: "dumbbell-wrist-curl", name: "ダンベルリストカール", equipment: "ダンベル" },
      { id: "reverse-wrist-curl", name: "リバースリストカール", equipment: "バーベル" },
      { id: "reverse-curl", name: "リバースカール", equipment: "EZバー" },
      { id: "wrist-roller", name: "リストローラー", equipment: "専用器具" },
      { id: "plate-pinch", name: "プレートピンチ", equipment: "プレート" },
      { id: "dead-hang", name: "デッドハング", equipment: "自重" },
    ],
  },
  脚: {
    大腿四頭筋: [
      { id: "high-bar-squat", name: "ハイバーバックスクワット", equipment: "バーベル" },
      { id: "front-squat", name: "フロントスクワット", equipment: "バーベル" },
      { id: "goblet-squat", name: "ゴブレットスクワット", equipment: "ダンベル" },
      { id: "leg-press", name: "レッグプレス", equipment: "マシン" },
      { id: "hack-squat", name: "ハックスクワット", equipment: "マシン" },
      { id: "leg-extension", name: "レッグエクステンション", equipment: "マシン" },
      { id: "bulgarian-split-squat-quad", name: "ブルガリアンスクワット（前もも）", equipment: "ダンベル" },
      { id: "walking-lunge-quad", name: "ウォーキングランジ", equipment: "ダンベル" },
      { id: "sissy-squat", name: "シシースクワット", equipment: "自重" },
      { id: "step-up", name: "ステップアップ", equipment: "ダンベル" },
    ],
    ハムストリングス: [
      { id: "romanian-deadlift", name: "ルーマニアンデッドリフト", equipment: "バーベル" },
      { id: "dumbbell-romanian-deadlift", name: "ダンベルルーマニアンデッドリフト", equipment: "ダンベル" },
      { id: "stiff-leg-deadlift", name: "スティッフレッグデッドリフト", equipment: "バーベル" },
      { id: "lying-leg-curl", name: "ライイングレッグカール", equipment: "マシン" },
      { id: "seated-leg-curl", name: "シーテッドレッグカール", equipment: "マシン" },
      { id: "standing-leg-curl", name: "スタンディングレッグカール", equipment: "マシン" },
      { id: "nordic-hamstring-curl", name: "ノルディックハムストリングカール", equipment: "自重" },
      { id: "single-leg-romanian-deadlift", name: "片脚ルーマニアンデッドリフト", equipment: "ダンベル" },
    ],
    臀部: [
      { id: "barbell-hip-thrust", name: "バーベルヒップスラスト", equipment: "バーベル" },
      { id: "glute-bridge", name: "グルートブリッジ", equipment: "自重" },
      { id: "cable-kickback", name: "ケーブルキックバック", equipment: "ケーブル" },
      { id: "hip-abduction-machine", name: "ヒップアブダクション", equipment: "マシン" },
      { id: "bulgarian-split-squat-glute", name: "ブルガリアンスクワット（臀部）", equipment: "ダンベル" },
      { id: "reverse-lunge", name: "リバースランジ", equipment: "ダンベル" },
      { id: "sumo-squat", name: "スモウスクワット", equipment: "ダンベル" },
      { id: "frog-pump", name: "フロッグポンプ", equipment: "自重" },
      { id: "single-leg-hip-thrust", name: "片脚ヒップスラスト", equipment: "自重" },
    ],
    内転筋: [
      { id: "hip-adduction-machine", name: "ヒップアダクション", equipment: "マシン" },
      { id: "cable-hip-adduction", name: "ケーブルヒップアダクション", equipment: "ケーブル" },
      { id: "cossack-squat", name: "コサックスクワット", equipment: "自重" },
      { id: "lateral-lunge", name: "サイドランジ", equipment: "ダンベル" },
      { id: "adductor-side-plank", name: "コペンハーゲンプランク", equipment: "自重" },
    ],
    ふくらはぎ: [
      { id: "standing-calf-raise", name: "スタンディングカーフレイズ", equipment: "マシン" },
      { id: "seated-calf-raise", name: "シーテッドカーフレイズ", equipment: "マシン" },
      { id: "donkey-calf-raise", name: "ドンキーカーフレイズ", equipment: "マシン" },
      { id: "single-leg-calf-raise", name: "片脚カーフレイズ", equipment: "自重" },
      { id: "leg-press-calf-raise", name: "レッグプレスカーフレイズ", equipment: "マシン" },
      { id: "dumbbell-calf-raise", name: "ダンベルカーフレイズ", equipment: "ダンベル" },
      { id: "tibialis-raise", name: "ティビアリスレイズ", equipment: "自重" },
    ],
    脚全体: [
      { id: "low-bar-squat", name: "ローバーバックスクワット", equipment: "バーベル" },
      { id: "smith-machine-squat", name: "スミスマシンスクワット", equipment: "スミスマシン" },
      { id: "bodyweight-squat", name: "自重スクワット", equipment: "自重" },
      { id: "jump-squat", name: "ジャンプスクワット", equipment: "自重" },
      { id: "barbell-lunge", name: "バーベルランジ", equipment: "バーベル" },
      { id: "sled-push", name: "スレッドプッシュ", equipment: "専用器具" },
    ],
  },
  腹: {
    腹直筋: [
      { id: "crunch", name: "クランチ", equipment: "自重" },
      { id: "sit-up", name: "シットアップ", equipment: "自重" },
      { id: "cable-crunch", name: "ケーブルクランチ", equipment: "ケーブル" },
      { id: "machine-crunch", name: "アブドミナルクランチ", equipment: "マシン" },
      { id: "hanging-leg-raise", name: "ハンギングレッグレイズ", equipment: "自重" },
      { id: "lying-leg-raise", name: "ライイングレッグレイズ", equipment: "自重" },
      { id: "reverse-crunch", name: "リバースクランチ", equipment: "自重" },
      { id: "ab-wheel-rollout", name: "アブローラー", equipment: "アブローラー" },
      { id: "decline-sit-up", name: "デクラインシットアップ", equipment: "自重" },
    ],
    腹斜筋: [
      { id: "russian-twist", name: "ロシアンツイスト", equipment: "自重" },
      { id: "cable-woodchop", name: "ケーブルウッドチョップ", equipment: "ケーブル" },
      { id: "side-plank", name: "サイドプランク", equipment: "自重" },
      { id: "bicycle-crunch", name: "バイシクルクランチ", equipment: "自重" },
      { id: "dumbbell-side-bend", name: "ダンベルサイドベント", equipment: "ダンベル" },
      { id: "hanging-knee-raise-twist", name: "ツイストハンギングニーレイズ", equipment: "自重" },
      { id: "heel-touch", name: "ヒールタッチ", equipment: "自重" },
    ],
    体幹: [
      { id: "front-plank", name: "フロントプランク", equipment: "自重" },
      { id: "dead-bug", name: "デッドバグ", equipment: "自重" },
      { id: "bird-dog", name: "バードドッグ", equipment: "自重" },
      { id: "pallof-press", name: "パロフプレス", equipment: "ケーブル" },
      { id: "hollow-body-hold", name: "ホローボディホールド", equipment: "自重" },
      { id: "mountain-climber", name: "マウンテンクライマー", equipment: "自重" },
      { id: "bear-crawl", name: "ベアクロール", equipment: "自重" },
      { id: "suitcase-carry", name: "スーツケースキャリー", equipment: "ダンベル" },
    ],
  },
  全身: {
    全身連動: [
      { id: "barbell-clean", name: "バーベルクリーン", equipment: "バーベル" },
      { id: "clean-and-press", name: "クリーン＆プレス", equipment: "バーベル" },
      { id: "dumbbell-thruster", name: "ダンベルスラスター", equipment: "ダンベル" },
      { id: "kettlebell-swing", name: "ケトルベルスイング", equipment: "ケトルベル" },
      { id: "kettlebell-clean-and-press", name: "ケトルベルクリーン＆プレス", equipment: "ケトルベル" },
      { id: "burpee", name: "バーピー", equipment: "自重" },
      { id: "devils-press", name: "デビルズプレス", equipment: "ダンベル" },
      { id: "medicine-ball-slam", name: "メディシンボールスラム", equipment: "メディシンボール" },
    ],
  },
};
