// URL is supplied over hidden stdin. This script never loads .env or production credentials.
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { neon } from '@neondatabase/serverless';
import { PgDialect } from 'drizzle-orm/pg-core';
import * as friends from '../app/lib/friends/queries.ts';
const expectedHost='ep-morning-moon-b378vfjy-pooler.c-4.ap-southeast-1.aws.neon.tech';
console.log('Ready for isolated validation-branch connection on hidden stdin.');
process.stdin.setRawMode?.(true);
const url=await new Promise(resolve=>{let data='';const receive=chunk=>{data+=chunk.toString();if(data.includes('\n')){process.stdin.off('data',receive);resolve(JSON.parse(data.trim()).url);}};process.stdin.on('data',receive);});
process.stdin.setRawMode?.(false);process.stdin.pause();
if(new URL(url).hostname!==expectedHost)throw Error('Only the dedicated expiring validation branch is allowed.');
const sql=neon(url),dialect=new PgDialect();
const query=statement=>{const q=dialect.sqlToQuery(statement);return sql.query(q.sql,q.params);};
const [a,b,c,d]=Array.from({length:4},()=>randomUUID());
const email=`v2-${b}@example.invalid`;
await sql`INSERT INTO users(id,email,created_at) VALUES (${a},${`v2-${a}@example.invalid`},now()-interval '30 days'),(${b},${email},now()-interval '30 days'),(${c},${`v2-${c}@example.invalid`},now()),(${d},${`v2-${d}@example.invalid`},now())`;
await sql`INSERT INTO user_profiles(user_id,height_cm,weight_kg,weekly_training_days) VALUES (${a},175,65,4)`;
let history=await sql`SELECT weekly_goal,estimated FROM training_goal_history WHERE user_id=${a} ORDER BY effective_on`;
assert.equal(history.length,2);assert.equal(history[0].weekly_goal,null);assert.equal(history[1].weekly_goal,4);assert.equal(history[1].estimated,false);
await sql`UPDATE user_profiles SET weekly_training_days=6 WHERE user_id=${a}`;
history=await sql`SELECT weekly_goal FROM training_goal_history WHERE user_id=${a} ORDER BY effective_on`;
assert.equal(history.length,2);assert.equal(history.at(-1).weekly_goal,6);
assert.equal((await query(friends.friendSettingsRead(b)))[0].shareTraining,false);
assert.equal((await query(friends.friendSearch(a,email,true))).length,0);
await query(friends.friendSettingsSave(b,'公開名',true,false));
assert.deepEqual(await query(friends.friendSearch(a,email.toUpperCase(),true)),[{id:b,name:'公開名'}]);
assert.equal((await query(friends.friendSearch(a,b,false))).length,1);
assert.equal((await query(friends.friendProfile(a,b))).length,0);
assert.equal((await query(friends.friendRequest(a,b))).length,1);
assert.equal((await query(friends.friendRequest(b,a))).length,0);
assert.equal((await query(friends.friendChange(a,b,'accept'))).length,0);
assert.equal((await query(friends.friendChange(c,b,'accept'))).length,0);
assert.equal((await query(friends.friendChange(b,a,'accept'))).length,1);
const session=randomUUID(),exercise=randomUUID();
await sql`INSERT INTO training_sessions(id,user_id,performed_at,memo) VALUES (${session},${b},now(),'PRIVATE MEMO')`;
await sql`INSERT INTO training_exercises(id,session_id,exercise_id,exercise_name,body_part,display_order) VALUES (${exercise},${session},'bench-test','ベンチプレス','胸',0)`;
await sql`INSERT INTO training_sets(training_exercise_id,set_number,weight_kg,reps) VALUES (${exercise},1,60,10)`;
let profile=(await query(friends.friendProfile(a,b)))[0];assert.equal(profile.shared,false);assert.deepEqual(profile.records,[]);
await query(friends.friendSettingsSave(b,'公開名',true,true));
profile=(await query(friends.friendProfile(a,b)))[0];assert.equal(profile.records.length,1);assert.equal(profile.records[0].exercises[0].sets[0].weightKg,60);
assert.doesNotMatch(JSON.stringify(profile),/PRIVATE MEMO|email|bodyFat|chat|photo|condition/);
assert.equal((await query(friends.friendProfile(c,b))).length,0);
assert.equal((await query(friends.friendChange(a,b,'remove'))).length,1);
assert.equal((await query(friends.friendProfile(a,b))).length,0);
assert.equal((await query(friends.friendRequest(a,b))).length,0);
await query(friends.friendRequest(c,d));assert.equal((await query(friends.friendChange(c,d,'cancel'))).length,1);
await query(friends.friendRequest(a,d));assert.equal((await query(friends.friendChange(d,a,'reject'))).length,1);
const results=await Promise.all(Array.from({length:35},()=>query(friends.friendQuota(c,'search'))));
assert.equal(results.filter(rows=>rows.length).length,30);
console.log('PASS: goal trigger, private defaults, opt-in exact email search, request/accept/reject/cancel/remove authorization, friend-only training fields, atomic daily quota.');
console.log('Fixtures remain only on the expiring isolated test branch; production data was not modified.');
