export const exerciseCategories = ['すべて', '胸', '背中', '肩', '腕', '脚', '腹筋'] as const;
export type ExerciseCategory = Exclude<(typeof exerciseCategories)[number], 'すべて'>;

export type ExerciseOption = {
  id: string;
  name: string;
  category: ExerciseCategory;
  equipment: string;
};

export const exerciseCatalog: ExerciseOption[] = [
  // 胸
  { id: 'bench-press', name: 'ベンチプレス', category: '胸', equipment: 'バーベル' },
  { id: 'incline-bench-press', name: 'インクラインベンチプレス', category: '胸', equipment: 'バーベル' },
  { id: 'decline-bench-press', name: 'デクラインベンチプレス', category: '胸', equipment: 'バーベル' },
  { id: 'dumbbell-press', name: 'ダンベルプレス', category: '胸', equipment: 'ダンベル' },
  { id: 'incline-dumbbell-press', name: 'インクラインダンベルプレス', category: '胸', equipment: 'ダンベル' },
  { id: 'dumbbell-fly', name: 'ダンベルフライ', category: '胸', equipment: 'ダンベル' },
  { id: 'incline-dumbbell-fly', name: 'インクラインダンベルフライ', category: '胸', equipment: 'ダンベル' },
  { id: 'chest-press', name: 'チェストプレス', category: '胸', equipment: 'マシン' },
  { id: 'pec-deck-fly', name: 'ペックデックフライ', category: '胸', equipment: 'マシン' },
  { id: 'cable-crossover', name: 'ケーブルクロスオーバー', category: '胸', equipment: 'ケーブル' },
  { id: 'cable-fly', name: 'ケーブルフライ', category: '胸', equipment: 'ケーブル' },
  { id: 'dip-chest', name: 'ディップス（胸）', category: '胸', equipment: '自重' },
  { id: 'push-up', name: '腕立て伏せ', category: '胸', equipment: '自重' },
  { id: 'wide-push-up', name: 'ワイドプッシュアップ', category: '胸', equipment: '自重' },
  { id: 'decline-push-up', name: 'デクラインプッシュアップ', category: '胸', equipment: '自重' },

  // 背中
  { id: 'deadlift', name: 'デッドリフト', category: '背中', equipment: 'バーベル' },
  { id: 'lat-pulldown', name: 'ラットプルダウン', category: '背中', equipment: 'ケーブル' },
  { id: 'close-grip-lat-pulldown', name: 'クローズグリップラットプルダウン', category: '背中', equipment: 'ケーブル' },
  { id: 'reverse-grip-lat-pulldown', name: 'リバースグリップラットプルダウン', category: '背中', equipment: 'ケーブル' },
  { id: 'barbell-row', name: 'ベントオーバーバーベルロウ', category: '背中', equipment: 'バーベル' },
  { id: 'pendlay-row', name: 'ペンドレイロウ', category: '背中', equipment: 'バーベル' },
  { id: 't-bar-row', name: 'Tバーロウ', category: '背中', equipment: 'バーベル' },
  { id: 'one-arm-dumbbell-row', name: 'ワンハンドダンベルロウ', category: '背中', equipment: 'ダンベル' },
  { id: 'dumbbell-row', name: 'ダンベルロウ', category: '背中', equipment: 'ダンベル' },
  { id: 'seated-row', name: 'シーテッドロウ', category: '背中', equipment: 'マシン' },
  { id: 'chest-supported-row', name: 'チェストサポートロウ', category: '背中', equipment: 'マシン' },
  { id: 'machine-row', name: 'マシンロウ', category: '背中', equipment: 'マシン' },
  { id: 'straight-arm-pulldown', name: 'ストレートアームプルダウン', category: '背中', equipment: 'ケーブル' },
  { id: 'cable-row', name: 'ケーブルロウ', category: '背中', equipment: 'ケーブル' },
  { id: 'pull-up', name: '懸垂', category: '背中', equipment: '自重' },
  { id: 'chin-up', name: 'チンニング（逆手）', category: '背中', equipment: '自重' },
  { id: 'back-extension', name: 'バックエクステンション', category: '背中', equipment: '自重' },

  // 肩
  { id: 'overhead-press', name: 'オーバーヘッドプレス', category: '肩', equipment: 'バーベル' },
  { id: 'military-press', name: 'ミリタリープレス', category: '肩', equipment: 'バーベル' },
  { id: 'shoulder-press', name: 'ダンベルショルダープレス', category: '肩', equipment: 'ダンベル' },
  { id: 'arnold-press', name: 'アーノルドプレス', category: '肩', equipment: 'ダンベル' },
  { id: 'machine-shoulder-press', name: 'マシンショルダープレス', category: '肩', equipment: 'マシン' },
  { id: 'side-raise', name: 'サイドレイズ', category: '肩', equipment: 'ダンベル' },
  { id: 'cable-side-raise', name: 'ケーブルサイドレイズ', category: '肩', equipment: 'ケーブル' },
  { id: 'machine-side-raise', name: 'マシンサイドレイズ', category: '肩', equipment: 'マシン' },
  { id: 'front-raise', name: 'フロントレイズ', category: '肩', equipment: 'ダンベル' },
  { id: 'rear-delt-fly', name: 'リアデルトフライ', category: '肩', equipment: 'マシン' },
  { id: 'bent-over-rear-raise', name: 'ベントオーバーリアレイズ', category: '肩', equipment: 'ダンベル' },
  { id: 'face-pull', name: 'フェイスプル', category: '肩', equipment: 'ケーブル' },
  { id: 'upright-row', name: 'アップライトロウ', category: '肩', equipment: 'バーベル' },
  { id: 'dumbbell-shrug', name: 'ダンベルシュラッグ', category: '肩', equipment: 'ダンベル' },

  // 腕
  { id: 'barbell-curl', name: 'バーベルカール', category: '腕', equipment: 'バーベル' },
  { id: 'ez-bar-curl', name: 'EZバーカール', category: '腕', equipment: 'EZバー' },
  { id: 'dumbbell-curl', name: 'ダンベルカール', category: '腕', equipment: 'ダンベル' },
  { id: 'incline-dumbbell-curl', name: 'インクラインダンベルカール', category: '腕', equipment: 'ダンベル' },
  { id: 'hammer-curl', name: 'ハンマーカール', category: '腕', equipment: 'ダンベル' },
  { id: 'concentration-curl', name: 'コンセントレーションカール', category: '腕', equipment: 'ダンベル' },
  { id: 'preacher-curl', name: 'プリーチャーカール', category: '腕', equipment: 'マシン' },
  { id: 'cable-curl', name: 'ケーブルカール', category: '腕', equipment: 'ケーブル' },
  { id: 'close-grip-bench-press', name: 'ナローベンチプレス', category: '腕', equipment: 'バーベル' },
  { id: 'skull-crusher', name: 'スカルクラッシャー', category: '腕', equipment: 'EZバー' },
  { id: 'dumbbell-triceps-extension', name: 'ダンベルトライセプスエクステンション', category: '腕', equipment: 'ダンベル' },
  { id: 'overhead-cable-extension', name: 'オーバーヘッドケーブルエクステンション', category: '腕', equipment: 'ケーブル' },
  { id: 'cable-pushdown', name: 'ケーブルプレスダウン', category: '腕', equipment: 'ケーブル' },
  { id: 'rope-pushdown', name: 'ローププレスダウン', category: '腕', equipment: 'ケーブル' },
  { id: 'dip-triceps', name: 'ディップス（上腕三頭筋）', category: '腕', equipment: '自重' },
  { id: 'diamond-push-up', name: 'ダイヤモンドプッシュアップ', category: '腕', equipment: '自重' },
  { id: 'wrist-curl', name: 'リストカール', category: '腕', equipment: 'ダンベル' },
  { id: 'reverse-wrist-curl', name: 'リバースリストカール', category: '腕', equipment: 'ダンベル' },

  // 脚
  { id: 'squat', name: 'バックスクワット', category: '脚', equipment: 'バーベル' },
  { id: 'front-squat', name: 'フロントスクワット', category: '脚', equipment: 'バーベル' },
  { id: 'goblet-squat', name: 'ゴブレットスクワット', category: '脚', equipment: 'ダンベル' },
  { id: 'hack-squat', name: 'ハックスクワット', category: '脚', equipment: 'マシン' },
  { id: 'smith-squat', name: 'スミスマシンスクワット', category: '脚', equipment: 'スミスマシン' },
  { id: 'bulgarian-split-squat', name: 'ブルガリアンスクワット', category: '脚', equipment: 'ダンベル' },
  { id: 'split-squat', name: 'スプリットスクワット', category: '脚', equipment: '自重' },
  { id: 'lunge', name: 'ランジ', category: '脚', equipment: 'ダンベル' },
  { id: 'walking-lunge', name: 'ウォーキングランジ', category: '脚', equipment: 'ダンベル' },
  { id: 'leg-press', name: 'レッグプレス', category: '脚', equipment: 'マシン' },
  { id: 'leg-extension', name: 'レッグエクステンション', category: '脚', equipment: 'マシン' },
  { id: 'leg-curl', name: 'レッグカール', category: '脚', equipment: 'マシン' },
  { id: 'seated-leg-curl', name: 'シーテッドレッグカール', category: '脚', equipment: 'マシン' },
  { id: 'romanian-deadlift', name: 'ルーマニアンデッドリフト', category: '脚', equipment: 'バーベル' },
  { id: 'dumbbell-romanian-deadlift', name: 'ダンベルルーマニアンデッドリフト', category: '脚', equipment: 'ダンベル' },
  { id: 'hip-thrust', name: 'ヒップスラスト', category: '脚', equipment: 'バーベル' },
  { id: 'glute-bridge', name: 'グルートブリッジ', category: '脚', equipment: '自重' },
  { id: 'hip-abduction', name: 'ヒップアブダクション', category: '脚', equipment: 'マシン' },
  { id: 'hip-adduction', name: 'ヒップアダクション', category: '脚', equipment: 'マシン' },
  { id: 'calf-raise', name: 'スタンディングカーフレイズ', category: '脚', equipment: 'マシン' },
  { id: 'seated-calf-raise', name: 'シーテッドカーフレイズ', category: '脚', equipment: 'マシン' },
  { id: 'bodyweight-squat', name: '自重スクワット', category: '脚', equipment: '自重' },

  // 腹筋
  { id: 'crunch', name: 'クランチ', category: '腹筋', equipment: '自重' },
  { id: 'sit-up', name: 'シットアップ', category: '腹筋', equipment: '自重' },
  { id: 'plank', name: 'プランク', category: '腹筋', equipment: '自重' },
  { id: 'side-plank', name: 'サイドプランク', category: '腹筋', equipment: '自重' },
  { id: 'leg-raise', name: 'レッグレイズ', category: '腹筋', equipment: '自重' },
  { id: 'hanging-leg-raise', name: 'ハンギングレッグレイズ', category: '腹筋', equipment: '自重' },
  { id: 'knee-raise', name: 'ニーレイズ', category: '腹筋', equipment: '自重' },
  { id: 'ab-wheel', name: 'アブローラー', category: '腹筋', equipment: 'アブローラー' },
  { id: 'cable-crunch', name: 'ケーブルクランチ', category: '腹筋', equipment: 'ケーブル' },
  { id: 'russian-twist', name: 'ロシアンツイスト', category: '腹筋', equipment: '自重' },
  { id: 'bicycle-crunch', name: 'バイシクルクランチ', category: '腹筋', equipment: '自重' },
  { id: 'mountain-climber', name: 'マウンテンクライマー', category: '腹筋', equipment: '自重' },
  { id: 'dead-bug', name: 'デッドバグ', category: '腹筋', equipment: '自重' },
];
